version: '3'

services:
  web:
    build: ./WEB
    container_name: drivent_front
    volumes:
      - build_react:/var/www/html
    depends_on:
      - api

  api:
    container_name: drivent_back
    build: ./API
    ports:
      - 5000:4000
    depends_on:
      - db
      - cache
    restart: always

  db:
    image: postgres:14
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - ./API/.env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: redis
    ports: 
      - 9736:6379
    restart: always
    env_file:
      - ./API/.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - web

volumes:
  build_react:
  postgres:
  cache:
  